### ISSUE TITLE
Banner RTL Support

### ISSUE THREAD

**Issue by Saifallak** [stechstudio/filament-impersonate#13]
can we customize the banner to support RTL?
it looks ugly in RTL

![image](https://user-images.githubusercontent.com/6053156/166099142-2fc48e01-c33e-425d-b9d5-ff4bf93e0134.png)

![image](https://user-images.githubusercontent.com/6053156/166099193-e5be08ec-8c14-4cba-8684-bcae5d604fe4.png)

**Comment by jszobody** [comment]
Do you want to submit a PR for this?

**Comment by Saifallak** [comment]
Sorry i can't help with this
I may help with #11 this week if u want

**Comment by jszobody** [comment]
I switched from using a `margin-left` on the button to `column-gap` on the container, which should now provide equal spacing in RTL mode. Can you upgrade to v2.5.1 and verify it looks good for you?
