### ISSUE TITLE
Localize Banner Strings.

### ISSUE THREAD

**Issue by Saifallak** [stechstudio/filament-impersonate#14]
can we customize the banner to text?
to support othe languages.
like in arabic it should be
```json
{
"leave": "انهاء",
"Impersonating user": "انتحال شخصية المستخدم",
}
```

BTW: not very sure of the Arabic translations, but you got the point right ?

![image](https://user-images.githubusercontent.com/6053156/166099142-2fc48e01-c33e-425d-b9d5-ff4bf93e0134.png)

![image](https://user-images.githubusercontent.com/6053156/166099193-e5be08ec-8c14-4cba-8684-bcae5d604fe4.png)

**Comment by jszobody** [comment]
It is already localized.

https://github.com/stechstudio/filament-impersonate/blob/5929c47c44b1ebf1ce3cb34c1a42ac20bda3970e/resources/views/components/banner.blade.php#L65-L68

This is using the "translation strings as keys" approach as documented here:

https://laravel.com/docs/9.x/localization#using-translation-strings-as-keys

So you can already customize these strings with a translation JSON file in your `lang` directory.
