### ISSUE TITLE
Cannot declare class STS\FilamentImpersonate\Impersonate, because the name is already in use when caching route

### ISSUE THREAD

**Issue by ziming** [stechstudio/filament-impersonate#34]
Hi,

In the latest update, when i run php artisan route:cache I will get this exception:

Cannot declare class STS\FilamentImpersonate\Impersonate, because the name is already in use when caching route

**Comment by jszobody** [comment]
Hi there, I'm trying to reproduce this. You're sure you are on version `2.14`? I don't get that error when caching routes. The `STS\FilamentImpersonate\Impersonate` class was moved in a recent update, it shouldn't be seeing that.

**Comment by jszobody** [comment]
Fixed in `2.15` just now, thanks for the heads up!
