### ISSUE TITLE
Filament Admin panel 2 support

### ISSUE THREAD

**Issue by tanthammar** [stechstudio/filament-impersonate#4]
I am unable to get this plugin to work in Filament Admin Panel v2.
Would love to get a hint on how to proceed.

**Comment by jszobody** [comment]
Hmm, give me a bit to spin up a fresh Filament v2 app. TBH I haven't even done that yet. I wrote this for v1, then received a PR request to make it v2 compatible, and haven't actually tried it out myself. Will do so here in a bit...

**Comment by jszobody** [comment]
I just tagged v2.1, can you upgrade and let me know if you still have any issues? It's working well for me now with these latest fixes.

**Comment by tanthammar** [comment]
@jszobody
I installed v2.1, thankyou :)
But Impersonation doesn't work. 
I can't access the Filament admin panel. 
I can access the rest of the site, as a logged in user, but when I try to access /admin/ I get the login form.

I added this to the user model:
```php
class User extends Authenticatable implements FilamentUser
{
    use HasApiTokens, HasFactory, Notifiable, UserHasTeams, HasRoles;

    public function canAccessFilament(): bool
    {
        return true;
    }

    public function canImpersonate(): bool
    {
        return true;
    }

    public function canBeImpersonated(): bool
    {
        return true;
    }
```

**Comment by jszobody** [comment]
Hmm, I was able to impersonate just fine with my fresh Filament v2 app.

It's worth pointing out though that the purpose of this package is for you (an admin) to impersonate a regular user in your "regular" app. It wasn't meant for you to impersonate another admin and use Filament itself as that other admin.

Does that make sense?

When you click the impersonation icon for one of your users, you should be redirected to your app homepage, and be able to navigate that as the impersonated user. In my case it's just a vanilla Jetstream app that I setup for testing.

**Comment by jszobody** [comment]
Have you customized the Filament auth guard by chance? 

`config('filament.auth.guard')`

**Comment by tanthammar** [comment]
The auth guard is default.
This is a fresh Laravel Breeze application, where I want all users to access the admin panel.

**Comment by MACscr** [comment]
> 

I assume your goal with the impersonate package then is to be able to test out their roles/permissions or whatever you set for the admin panel?

**Comment by tanthammar** [comment]
@MACscr 
I have different fields, table columns, views, actions and more, based on the user role. Want to impersonate, to give support to customers. To make sure I see - what they see.

**Comment by tanthammar** [comment]
@jszobody Thank you for assisting me via Discord!
Enabling the AuthenticateSession middleware did the trick.
For other Breeze users :)
