### ISSUE TITLE
error filamentManager::getCurrentPanel()

### ISSUE THREAD

**Issue by williamengbjerg** [stechstudio/filament-impersonate#43]
Get this error message when I try to impersonate a user. 

`Call to undefined method Filament\FilamentManager::getCurrentPanel()` - Using jetstream.  Livewire 2 - any idea?

**Comment by jszobody** [comment]
Are you both using Filament v3?

**Comment by zabaala** [comment]
@jszobody I'm using V2.

**Comment by jszobody** [comment]
Ah. v3 of this package is only meant for Filament v3, that would explain the error. I need to add that requirement in the composer.json file to prevent folks from accidentally upgrading.

**Comment by jszobody** [comment]
@williamengbjerg Please install `^2.19` if you're using Filament v2 still. The latest v3 is for Filament v3 (beta right now, will be production tomorrow). 

I've removed the 3.0 release that allowed this issue, and just tagged 3.1 which has a dependency for Filament v3. If you uninstall and simple reinstall the package I believe it will now know to pick v2.
