### ISSUE TITLE
Route [filament.auth.login] not defined.

### ISSUE THREAD

**Issue by KeyMe29** [stechstudio/filament-impersonate#45]
Clicking on the impersonate button/icon cause a RouteNotFoundException "Route [filament.auth.login] not defined" in routes/web.php

**Comment by jszobody** [comment]
I don't think that is an error in this package.

See our routes file, that route name is not in there:

https://github.com/stechstudio/filament-impersonate/blob/master/routes/web.php

In fact the string "filament.auth.login" doesn't appear anywhere in this package. 

I think this error is in your own app, from what I can tell. Let me know if you determine there is some other issue in this package giving you trouble.
