### ISSUE TITLE
Enable to show banner

### ISSUE THREAD

**Issue by cntabana** [stechstudio/filament-impersonate#47]
I have an issue to display the banner . I have investigated the code. I found that the issue lies in the following file:

https://github.com/stechstudio/filament-impersonate/blob/master/src/FilamentImpersonateServiceProvider.php#L37

In the original code snippet, the Filament::registerRenderHook method is used as follows:

```
Filament::registerRenderHook(
            'body.start',
            static fn (): string => Blade::render("<x-filament-impersonate::banner/>")
);
```

To resolve the issue, you can change it to the following code:

```
FilamentView::registerRenderHook(
            'panels::body.start',
            static fn (): string => Blade::render("<x-filament-impersonate::banner/>")
);
```

 If you're okay with it, I can create a pull request to implement the changes.

Let me know what you think.

By the way, thank you for your plugin

**Comment by aeq-dev** [comment]
+1
Any updates here ? thanks :)

**Comment by malle-pietje** [comment]
I simply fixed the issue by adding this to the `AppServiceProvider`:
```php
    /**
     * Register any application services.
     */
    public function register(): void
    {
        FilamentView::registerRenderHook(
            'panels::body.start',
            fn (): string => Blade::render('<x-impersonate::banner/>'),
        );
    }
    ```

**Comment by cntabana** [comment]
I have submitted a pull request now.
