### ISSUE TITLE
[Suggestion] Submit to Filament plugins site

### ISSUE THREAD

**Issue by nikspyratos** [stechstudio/filament-impersonate#50]
Hi there,

I noticed this package isn't visible in the Filament plugins directory? You can submit it here: https://github.com/filamentphp/filamentphp.com/blob/main/README.md#contributing

**Comment by jszobody** [comment]
Interesting. It used to be! Curious that they didn't transition existing plugins when they built the new site. 

I'll work on submitting there, thanks for the heads up.
