### ISSUE TITLE
Problem to impersonate with admin guard

### ISSUE THREAD

**Issue by gboquizosanchez** [stechstudio/filament-impersonate#55]
![image](https://github.com/stechstudio/filament-impersonate/assets/20032391/5debcc0f-1217-4e52-9caa-c02776ed59e2)

I have two guards, admin and the default web. When I'm trying to impersonate an admin as a default user, I'm getting this issue.

What I'm doing wrong? If you need more information, please, let me know, and I'll share you what you need.

Thanks in advance!

**Comment by MarJose123** [comment]
> ![image](https://user-images.githubusercontent.com/20032391/271732963-5debcc0f-1217-4e52-9caa-c02776ed59e2.png)
> 
> I have two guards, admin and the default web. When I'm trying to impersonate an admin as a default user, I'm getting this issue.
> 
> What I'm doing wrong? If you need more information, please, let me know, and I'll share you what you need.
> 
> Thanks in advance!

Did you add the traits to our authenticable model?

**Comment by gboquizosanchez** [comment]
Yeah, and not working.

```
use Lab404\Impersonate\Models\Impersonate;

final class Admin extends Authenticatable implements FilamentUser, MustVerifyEmail
{
    use Impersonate;
    
    ...
}

---

use Lab404\Impersonate\Models\Impersonate;

final class User extends Authenticatable implements FilamentUser, MustVerifyEmail
{
    use Impersonate;
    
    ...
}
```

Do you mean this, right?

**Comment by MarJose123** [comment]
how about in your filament panel? did you declare the guard should be used?

**Comment by gboquizosanchez** [comment]
I'm logged as "admin" and my impersonate button is like:

```
Impersonate::make('impersonate')
    ->guard('web')
    ->link()
    ->iconSize(IconSize::Small)
```

I need to change something in laravel-impersonate config?

**Comment by MarJose123** [comment]
> I'm logged as "admin":
> 
> ```
> public function panel(Panel $panel): Panel
> {
>     return $panel
>         ->authGuard('admin')
>         ...
> }
> ```
> 
> and my impersonate button is like:
> 
> ```
> Impersonate::make('impersonate')
>     ->guard('web')
>     ->link()
>     ->iconSize(IconSize::Small)
> ```
> 
> I need to change something in laravel-impersonate config?
> 
> canImpersonate is automatically established as `true`.

I'm not quit sure now what is the cause of issue you encountered, there is no needed really to change in the config file, maybe you need to revisit the README file and check on what steps you missed and if you are caching you laravel you need to clear it.

**Comment by gboquizosanchez** [comment]
At last, I have achieved the way to impersonate the user. But, when I put the banner component, I got this message:

![image](https://github.com/stechstudio/filament-impersonate/assets/20032391/9c1ce03e-5d38-4d99-938d-eb01e6e19ca2)

But in debugbar the user is logged, so, I don't know what it's happening...
