### ISSUE TITLE
Error on impersionate

### ISSUE THREAD

**Issue by vitormcorrea** [stechstudio/filament-impersonate#57]
Hey guys.

I have the following error when clicking the button to impersonate

Call to undefined method Filament\FilamentManager::getCurrentPanel()

Has anyone ever get this problem?

<img width="1756" alt="Captura de Tela 2023-10-05 às 07 27 14" src="https://github.com/stechstudio/filament-impersonate/assets/3817446/63409f67-1ff1-4791-9ec6-54826be837eb">

**Comment by jszobody** [comment]
What version of Filament are you using?

**Comment by jszobody** [comment]
Make sure then you're using version 2 of this package. Use `^2.0` in your composer.json file.
