### ISSUE TITLE
registerRenderHook(): Argument #1 ($name) must be of type string, null given

### ISSUE THREAD

**Issue by robert-abram** [stechstudio/filament-impersonate#67]
During composer  update to 3.6 this error

```
Filament\Support\Facades\FilamentView::registerRenderHook(): Argument #1 ($name) must be of type string, null given, called in /app/vendor/stechstudio/filament-impersonate/src/FilamentImpersonateServiceProvider.php on line 40
```

**Comment by jszobody** [comment]
@robert-abram 

v3.6 introduced a new config value:

https://github.com/stechstudio/filament-impersonate/blob/e559289a0f597fcb087a8863a07def495665a53d/config/filament-impersonate.php#L14

https://github.com/stechstudio/filament-impersonate/blob/e559289a0f597fcb087a8863a07def495665a53d/src/FilamentImpersonateServiceProvider.php#L41

Have you published the I'm not sure why it's `null` for you. Can you try running `php artisan config:clear` to see if that fixes it?

**Comment by joaovdiasb** [comment]
> 'render_hook' => env('FILAMENT_IMPERSONATE_BANNER_RENDER_HOOK', 'panels::body.start'),

Yeah, it is a break change for those who have the config published

**Comment by jszobody** [comment]
Got it, will stick the default value in the service provider config() call.

(I thought published config files got merged on top of the package default config though? Need to read up on how Laravel handles that...)

**Comment by joaovdiasb** [comment]
> Got it, will stick the default value in the service provider config() call.
> 
> (I thought published config files got merged on top of the package default config though? Need to read up on how Laravel handles that...)

The published configuration replaces the vendor's

**Comment by jszobody** [comment]
Laravel provides a `$this->mergeConfigFrom` method for packages to merge in the published config, but it only works with top-level config values, not nested. We have this new config nested under `banner`, that's our issue.

Will get the default value in there for a quick fix. Might consider flattening the whole config file in a future major (breaking) release to merge properly.

**Comment by jszobody** [comment]
@robert-abram @joaovdiasb v3.6.1 is tagged, you should be good to go.
