### ISSUE TITLE
Support for page action

### ISSUE THREAD

**Issue by jszobody** [stechstudio/filament-impersonate#7]
Right now this is only available as a table action. Would be nice to be available as a page action as well, so it could be added to a View User page, for example.

**Comment by jacksleight** [comment]
This would be really useful. It would also be nice to have the option to use a regular text button instead of an icon.

If anyone needs this immediately you can do this for now:

```php
use STS\FilamentImpersonate\Impersonate;

class ViewUser extends ViewRecord
{
    // ...

    protected function getActions(): array
    {
        return array_merge([
            Pages\Actions\ButtonAction::make('impersonate')
                ->action(function () {
                    Impersonate::impersonate($this->record);
                }),
        ], parent::getActions());
    }
}
```

**Comment by josefbehr** [comment]
@jszobody I just added this in https://github.com/stechstudio/filament-impersonate/pull/27, please test, if you can
