### ISSUE TITLE
Table Impersonate does not work with widgets

### ISSUE THREAD

**Issue by soymgomez** [stechstudio/filament-impersonate#73]
Hello,

If you have a table in which there are widgets that interact with the table(`InteractsWithPageTable `) when executing the impersonate action another widget event is sent, which causes that the user is not redirected correctly.

Do you know any way to stop this from happening?

Best regards

**Comment by jszobody** [comment]
I don't, not offhand. I haven't used this with widgets. Can you provide a minimal example of how to reproduce? Something I can grab and test out directly?

**Comment by jszobody** [comment]
Closing until there is a minimal reproducible test case or example we can work off of.
