### ISSUE TITLE
Trouble on impersonate from resources other than UserResource

### ISSUE THREAD

**Issue by z4yed** [stechstudio/filament-impersonate#74]
I have a resource named `InstructorResource`. The `Instructor` model has a relational `user` method which belongs to `User` model. 

I am trying to impersonate from InstructorResource by:

```php
return $table
       ->actions([
                Impersonate::make()
                    ->redirectTo('/instructor'),

                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
            ]),
```

From the `UserResource` class, it is working perfectly though. Is it possible to impersonate from `InstructResource`?

**Comment by z4yed** [comment]
```php
->actions([
  Impersonate::make()
      ->redirectTo('/instructor')
      ->action(fn($record) => $this->impersonate($record->user)),
  Tables\Actions\ViewAction::make(),
  Tables\Actions\EditAction::make(),
])
```
### This code return the below error.

![image](https://github.com/stechstudio/filament-impersonate/assets/54860522/c9a676c7-49b2-4afb-9cd8-fd005fa74e94)

**Comment by KonstantinosVazaios** [comment]
I am having the same issue. Tried to override the record method but did not work as well

**Comment by AurelDemiri** [comment]
@z4yed This should work:

```php
            ->actions([
                Impersonate::make()
                    ->action(fn(Interpreter $record, Impersonate $action) => $action->impersonate($record->user)),
                Tables\Actions\EditAction::make(),
            ])
```

**Comment by z4yed** [comment]
@AurelDemiri awesome! Thanks.
