### ISSUE TITLE
ImpersonateManager does not leave the impersonation

### ISSUE THREAD

**Issue by ghost** [stechstudio/filament-impersonate#77]
I'm on Laravel 11

When I click `Leave` in the banner, nothing happens.

I've narrowed it down to the `ImpersonateManager` `leave` method not working.

Which as to do with the package this package uses.

**Comment by kejedi** [comment]
For now I've just overwritten the route to log the user right out:

```php
Route::get('filament-impersonate/leave', function () {
    Auth::logout();

    return redirect('/login');
})->name('filament-impersonate.leave');
```

**Comment by kejedi** [comment]
A better workaround for now:

```php
Route::middleware(config('filament-impersonate.leave_middleware'))
    ->get('filament-impersonate/leave', function () {
        $manager = app('impersonate');

        if ($manager->isImpersonating()) {
            $user = $manager->findUserById($manager->getImpersonatorId());

            Auth::quietLogout();

            Auth::quietLogin($user);

            $manager->clear();
        }

        return redirect('/');
    })
    ->name('filament-impersonate.leave');
```

**Comment by AurelDemiri** [comment]
I have this issue as well using Laravel 11.

What "fixed" it for me was removing my global scopes:

`    protected static function booted(): void
    {
        if (auth()->check()) {
            static::addGlobalScope(new ViewableByCurrentUser());
        }
    }`

**Comment by manbhatia** [comment]
> I have this issue as well using Laravel 11.
> 
> What "fixed" it for me was removing my global scopes (not what I wanted to do) so I just added a check for the leave route:
> 
> ```
>     protected static function booted(): void
>     {
>         // Workaround for filament impersonate leave bug.
>         if (request()?->route()?->getName() !== 'filament-impersonate.leave') {
>             static::addGlobalScope(new ViewableByCurrentUser());
>         }
>     }
> ```

Worked for me as well. Thanks!

**Comment by jszobody** [comment]
Ah, global scopes would make sense. Interesting.

Any thoughts on how this package could provide an option or hook for this? I'm wondering if the leave route should use `withoutGlobalScope()` somewhere.

**Comment by AssisJuniorFacilis** [comment]
I'm having the same problem, in my case I have a global scope for listing my users, will this affect the functioning of the scope? I need the scope to also work with the impersonated user

**Comment by EG-Mohamed** [comment]
> A better workaround for now:
> 
> Route::middleware(config('filament-impersonate.leave_middleware'))
>     ->get('filament-impersonate/leave', function () {
>         $manager = app('impersonate');
> 
>         if ($manager->isImpersonating()) {
>             $user = $manager->findUserById($manager->getImpersonatorId());
> 
>             Auth::quietLogout();
> 
>             Auth::quietLogin($user);
> 
>             $manager->clear();
>         }
> 
>         return redirect('/');
>     })
>     ->name('filament-impersonate.leave');

Small update

```php
Route::middleware(config('filament-impersonate.leave_middleware'))
    ->get('filament-impersonate/leave', function () {
        $manager = app('impersonate');

        if ($manager->isImpersonating()) {
            $user = $manager->findUserById($manager->getImpersonatorId());


            \Illuminate\Support\Facades\Auth::quietLogout();

            \Illuminate\Support\Facades\Auth::quietLogin($user);

            $manager->clear();
        }
        return redirect(session()->pull('impersonate.back_to','/'));
    })
    ->name('filament-impersonate.leave');
```

use `return redirect(session()->pull('impersonate.back_to','/'));` to redirect back to correct direction not the /
