### ISSUE TITLE
Undefined type 'App\Models\IsFilamentUser'.

### ISSUE THREAD

**Issue by seabasss** [stechstudio/filament-impersonate#8]
In the doc it says `use IsFilamentUser`, but I get the message `Undefined type 'App\Models\IsFilamentUser'.` and it can't find anything to import. It seems to work without `IsFilamentUser`, but am I doing anything wrong or is the example wrong?

```
class User implements FilamentUser {
    use IsFilamentUser;
    
    public function canImpersonate()
    {
        return true;
    }
}
```

**Comment by jszobody** [comment]
Ah, right. That trait was part of Filament v1 and is no longer needed in Filament v2. I just updated the docs.
