### ISSUE TITLE
It does not work with Multi-Tenant app

### ISSUE THREAD

**Issue by mansoorkhan96** [stechstudio/filament-impersonate#80]
I am trying to add impersonate to multi-tenant app. when i hit impersonate action it throws 403 error.

```env
FILAMENT_IMPERSONATE_REDIRECT=/console
```

Also tried `FILAMENT_IMPERSONATE_REDIRECT=/console/1` to see if it cannot find the tenant or something but no luck.

Tried to pass a custom url to `redirectTo()` method and also tried to set tenant before redirecting but still does not work.

Am i missing something that should be added to make it work on multi-tenant?

**Comment by jszobody** [comment]
Multi-tenancy can be implemented in 100 different ways. I don't know how yours works, I can't tell you what needs to be handled. 

The underlying impersonate package does fire some events when impersonation happens, maybe you can listen for those events and wire up the appropriate tenant that way?

https://github.com/404labfr/laravel-impersonate?tab=readme-ov-file#events

**Comment by altomar** [comment]
in my case, I have 2 panels, one with multi-tenancy and the other without. When I impersonate a user that does not belong to a tenant, I get memory leak. Then I added the user to a tenant and then it worked as normal.

**Comment by mansoorkhan96** [comment]
Hey @altomar 

I did not hit the memory issues but here is what worked for me in case it helps you.

In your web.php, define a custom route for impersonate.

```php
Route::get('/impersonate/{user}', ImpersonateController::class)->name('impersonate');
```

Create the ImpersonateController.

```php
use App\Models\User;
use Filament\Support\Concerns\EvaluatesClosures;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use STS\FilamentImpersonate\Concerns\Impersonates;

class ImpersonateController extends Controller
{
    use EvaluatesClosures; // We need this trait in order use the impersonate feature from the plugin
    use Impersonates;

    public function __invoke(Request $request, User $user): RedirectResponse
    {
        abort_unless(auth()->check() && auth()->user()->is_admin, 403);

        return $this->impersonate($user); // we are using the function from the plugin.
    }
}
```

Finally in UserResource, pass the custom url to Impersonate action.

```php
->actions([
        Impersonate::make()
            ->url(fn (User $record) => route('impersonate', $record)),
])
```
