### ISSUE TITLE
Always impersonating myself

### ISSUE THREAD

**Issue by kevin-oxygen** [stechstudio/filament-impersonate#81]
In the last couple of days I noticed that when I go to impersonate any user, it "impersonates" the user I'm signed in with. Then when I "Leave" it 500 errors and I'm stuck until logging out. This plugin was working 100% perfectly until this so I'm sure I probably messed something up.

Any insight into how I should troubleshoot this issue would be greatly appreciated.

Thanks in advance.

**Comment by jszobody** [comment]
Offhand I don't know what broke, this package hasn't changed in a while. If you can reproduce it in a simple github repo example, I'd be happy to take a look.
