### ISSUE TITLE
Laravel 11 compatibility?

### ISSUE THREAD

**Issue by erikpb** [stechstudio/filament-impersonate#98]
I seem to be getting this error when installing in a Laravel 11 project:

`Warning: require(/var/www/html/vendor/composer/../symfony/string/Resources/functions.php): Failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 41`

**Comment by V13Axel** [comment]
This package should install and work just fine on Laravel 11, and I just tested on a fresh Filament project to be extra sure. Was there any additional context around that error? It appears to be an error loading something from `symfony`, unrelated to this package.

**Comment by erikpb** [comment]
Yes you are right, sorry about that, false alarm.
